site_name: Crow 64 Wiki
site_url: https://chipchippity.github.io/Catastrophe-Crow-Wiki/
copyright: Copyright &copy; 2024 <a href="https://discord.gg/khV4fdDYpv" target="_blank">Catastrophe Crow 64 Wiki</a>, Worked on by the <a href="/credits">CC64 Discord Server</a>.
site_description: CC64 Wiki
site_author: CC64 Discord Server.
theme:
  name: slate
  locale: en
  logo: MCrow.png
  favicon : MCrow.png

nav:
  - 'index.md'
  - 'main.md'
  - 'Recap.md'
  - 'credits.md'

markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

extra_css:
    - css/custom.css
